apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:emIu+V9h7JNoXRBr94cVlqMDBbb+6NmpLzh5FmzGyAggxgnCr8DZ3Q==,iv:LpnIPrroKw23hlsQaGO5R3zCvyzYzZJAabCvSyETj/w=,tag:y3/9tbnA7tRNjtNIYS4bzQ==,type:str]
sops:
  age:
    - recipient: age1qrg4hjfmt4gc4x3tt07pqx795t6vy93qcz5lhavtwcsxuk3029dsvlngka
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNUZycUFma0tOekdvbjIx
        bTJhMlBnakI2TGxrMWFjaUM0dUxBQ01ZWnhrCjlHS2QrcCs2REh4WjJrTFpoOTlR
        MjNwZ0VtWUNJRFdIRlVPdjAvWGYwUHcKLS0tIEtWZFRQek84TDRPMkcvaXNyNloy
        SzdPckg3a3ZLWEErQWdVdzRCeUVFYkEKElaoef8mJvvbiPRJHNvq+WSjZbpCyJqv
        mdoqIurLHlJOEfqsxH4x8ayBLSYNsfP5dGdM8JlCm0KeEuEy6IE5Mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T19:55:47Z"
  mac: ENC[AES256_GCM,data:J9QdwaPujVjq23MD9exoiplnon6M/4UoKVSMYTcf8bpxjzDGoAUDS57lXAyBEFoPTp2Qxll/IuXGRHhQYsGfWCn5l9oXzzJc8dINYZsmEGYuZgfWj1W9nnbj4YfmiCYuK/0/jcIo+l5UFFko75i6dUZTsGix0Wh6xfj0l1tabrU=,iv:I1R/tsFi2wc5DwrW2qDAaSnG8aDRkOxo6DxvVZMfcCY=,tag:6EXWcBzIpzl7IJzY2s2DMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
