apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:aqqY3nFkSbLEL3EwF1P57BbT,iv:ntXw/wnyIQW4N3SLO5XZu3tdF3OAWpLlP+suxG1wG1g=,tag:lfcCldj1o8ZGqtykei1x7A==,type:str]
sops:
  age:
    - recipient: age1qrg4hjfmt4gc4x3tt07pqx795t6vy93qcz5lhavtwcsxuk3029dsvlngka
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQajNjc3VnWE9wWEIyZmZI
        Ym42MDVYZHZRaEtpQU9abmViNzNoSmI2T3dRCjBQa0lVN0tPTTVZRlVPUWtMWVBr
        ZEdRaDJTMmx3ejFLUGlPbDVDVnY1UEUKLS0tIFUyMU82WlJYNWxuZ3Fsd0QrOGdI
        MW5qMjIyM1YweGlKNExKUmlNOEV6SE0KF1dwXrBM96XXqntdD+PMM2vasr14uPte
        CQxCtm3kJAui/6RSTtQqiy2IsWFdx9EZxTniz+xr8hzsHjMf97IqZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T19:55:47Z"
  mac: ENC[AES256_GCM,data:GPjcXGcax/wIpCxhzhydO/5JCwxVkjm9/hJzMfa6c8guOVqLHQBiXj3CHuBmeMgNZyJTuMgLMAP6UyF+3rSoDh2LOg1t/RSuzqC2DlzpHQvvF4cc1xksFlMsQZY8HjPG0atPXLTrAQ6sO6aOe86FjTQk6glaedfKiRcSfi7YlPM=,iv:Y5QMnNpF/zFwnH+ckVtbGkhBhgBeOHSBMGMy3Q54Xqg=,tag:2i9fzNw7tkcE5bcwOHPdTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
