apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:YceujnK1Wbj7GFcxLI9ZM4B63pfXSebmtX7whvBHf9k=,iv:Nxv7AEz5NwN+EfNXJtq+NejobMmilj1DEavsiKtbhVo=,tag:PoyJpFGtRrzLON0IC37QIg==,type:str]
sops:
  age:
    - recipient: age1qrg4hjfmt4gc4x3tt07pqx795t6vy93qcz5lhavtwcsxuk3029dsvlngka
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZEpxaXNXYnhDTVJ2cGs1
        TXh1TTQyZG5LaUJHQlRubGRZSDV3UE40Y1FRClpKL0VOQVVwN0FRcGFTeFBxK1N6
        MWtCUUQyU3dVSTJzRHVpSkJnekw5emcKLS0tIGZhU3RMcGJZNHNhTFhqMVhuZ0FE
        ZEtSQ2pwTlZaRzRKU0xCR2wyVnZVc0UKZn+g7srKnYCH4zYzrnjvfrzr/XLcilgO
        LV3QDfajs+JSRtBDlw9SHDqBj0rdOX34GLytoFk4SCp7wZ/z+JMdyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T19:55:47Z"
  mac: ENC[AES256_GCM,data:x0ZDU/EbQegNi5AhllbyZsG6VX1MAVE2/K0pnk0YgmhK8ooZ8EYd5Wl96SxjnYsaawZVGVNgBzTrpe9DedmGd+ISQBHQFaRMkq9gWcctEjc44GnQFY/+cWN9JvMhSIRe5j2LTbcfONBtpaE90/Vpr1zlEvedF6Jv4trweQqC3Oc=,iv:GBi/Nc2UzGWUWCzFJg/vc0SpqgCF9mzYzEEFy/yTR98=,tag:HfOiKyP2uLsPEGb36qRkkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
