apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:O1X7U3W9mZocWF7hKTjIXv6NyI70iD8BiAijvpsNqKQVh+ccbM4yIED/cEqBIIPFngawytYkQ7zHpb9Q0NlyDKYJ9skEYXlnOG4xHFbbtI45Ij9buL4hwVtbVY6/Z4PYLrvx2upgLLu/RG4ldG/j/TblMujxYElBzbo9C2iHPBokCBukz5NbVnkog398ek13xi+U1nId6igac3J1MznYZgPMqwQRt+Dg0D6lzus/YwWfoF3z,iv:ioGcYLanBN+1lxu7eBMMkWbolNsfaEVJ8iHSchRsnio=,tag:I25R8Q/b5J9EQya563a3Ew==,type:str]
sops:
  age:
    - recipient: age1qrg4hjfmt4gc4x3tt07pqx795t6vy93qcz5lhavtwcsxuk3029dsvlngka
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNU5pTHJRcjJ4MHF3TDcx
        NlJ5ZmpCeDNsWmJzdFMwQ1dwN0J0N0N1MEdnCnVDaXJ6QmR6YjlTSjRxZG5mdlMr
        bjR6eDVoTVdTZTViUW9pMm11OEhmSFUKLS0tIFFkZ1NEandMQ2tQL1NHdjY5MzN5
        ZllYUEJGT2VjUFFhQ2p3V3krVFo5dDAKsGSM5FYxhjQ2bJxArtwcjThvjr9HNRUH
        4Y+aINlE7Uucr8ALDx9clMPtGPNwVzMLNHCcbZLw7IrRDMR1mCmqyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T19:55:47Z"
  mac: ENC[AES256_GCM,data:UENQ4AOX3PsD4UZDYZXpQHLPJX5egdQcux1Pv8y+NuR65/XQCE9UeaXSLkBomOmfcViGjev5Lbgw1wJjgZrpwhER+KocOHMTyEPlmWvTUgxmLrpW7m4LHZyDzTNlouJNhKxJqnJEmPOybwrKS3iC44t0ZMpsW2zhYO5KZeRU1Rw=,iv:VrNHMtmWkCr8B3TiPTUQJykLJ+luqIdVFdJcnuNjMmw=,tag:9N5WbU50wR6r8yBgD3i/og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
