apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZtYt9oZAY20v4JNyYGFzjs/8UJnT53guwj44iSNhxxvZENN/rJyTHw==,iv:OStVuVwMCWM4zjqp8xesZwSQi0VZoOEPyeYieVmkrv8=,tag:NjvfauxS2fgoJCWVQmyHgQ==,type:str]
sops:
  age:
    - recipient: age1qrg4hjfmt4gc4x3tt07pqx795t6vy93qcz5lhavtwcsxuk3029dsvlngka
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncU5xRis1ajhmRThyK3JF
        Q1J2dGJtTEQ1djVqckZ3OS9rZ2YvTGRwMDNzCmdiNHAxZU5pMkR2SjByV0pCQ0kv
        STFZUnJDeCt5dEhPOE96Z0ZzOENBTXcKLS0tIHdhMEZjVnB0QmNTSVZLQXhZZm1G
        RWo3RUVBclgwcWJDblhpQVpCNkJxUTAKG9XICuzWjGOX4szDAVcLdYMj2hTp34rT
        xEQOLNtO0VmkXieNMwR3vhsoi3bFgdDSRa9pI97t7ESV5HGwJ0cFzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T19:55:47Z"
  mac: ENC[AES256_GCM,data:Zr/bWKwpWTwP/gzOnYrBbiLTcMsCf3VFKwiSvZRzgSu8OSavl671PgY7xgKW5wkPPsmtzZflA9Yl4MWyzBBmO9Or5bG6z7m7vJdVLGBYAP3MJt28BZJX+mlazwgXdLVjPZp0kGI8qmpQfSiQP64iezKfLk1NbCOCAVSCtloDnA8=,iv:94SbJNT1EOD5539BVkNE/5Fy6lfMw3PEvoy7c0/f4Fc=,tag:cJypJqzu4iugM2y2MEm7gw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
